// Application:

export const START_APPLICATION_LOADING = 'START_APPLICATION_LOADING'
export const STOP_APPLICATION_LOADING = 'STOP_APPLICATION_LOADING'
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
